### ISSUE TITLE
distlib required for "Bootstrap from source"?

### ISSUE THREAD

**Issue by timrobotson** [colcon/colcon.readthedocs.org#33]
I was just going through https://colcon.readthedocs.io/en/released/developer/bootstrap.html to build colcon from source. On the first "build the sources" step it failed because I didn't have distlib installed. 

```
(colcon-venv) tim@ub191:~/projects/colcon/colcon-from-source$ ./src/colcon-core/bin/colcon build --paths src/*
Traceback (most recent call last):
  File "./src/colcon-core/bin/colcon", line 59, in <module>
    from colcon_core.package_identification.python \
  File "/home/tim/projects/colcon/colcon-from-source/src/colcon-core/colcon_core/package_identification/python.py", line 9, in <module>
    from distlib.util import parse_requirement
ModuleNotFoundError: No module named 'distlib'
```

Installing distlib via pip fixed the issue:

```
(colcon-venv) tim@ub191:~/projects/colcon/colcon-from-source$ pip install distlib
Collecting distlib
Installing collected packages: distlib
Successfully installed distlib-0.2.8
(colcon-venv) tim@ub191:~/projects/colcon/colcon-from-source$ ./src/colcon-core/bin/colcon build --paths src/*
Starting >>> colcon-core
running egg_info
...
```

Does distlib need to be added to the requirements.txt file? 

I'm building on Ubuntu 18.04 with Python 3.6

**Comment by dirk-thomas** [comment]
> Does distlib need to be added to the requirements.txt file?

Indeed, fixed by #34.
